-- Database-enforced bookkeeping: updated_at, order status history, and
-- orders/payments consistency. Done as triggers so every writer is covered
-- (Go services, raw SQL, seeds) with no per-call-site code.

-- ---------------------------------------------------------------------------
-- 1. orders.currency
-- ---------------------------------------------------------------------------

-- AutoMigrate also adds this from the model, with the same default.
ALTER TABLE orders ADD COLUMN IF NOT EXISTS currency varchar(10) NOT NULL DEFAULT 'usd';

-- Existing orders default to 'usd'; take the real value from their payment.
UPDATE orders o SET currency = lower(p.currency)
FROM payments p
WHERE p.order_id = o.id AND o.currency <> lower(p.currency);

-- ---------------------------------------------------------------------------
-- 2. updated_at maintained by the database
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION trg_set_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END $$;

-- Raw updates (e.g. the used_count increment uses UpdateColumn) skip GORM's
-- autoUpdateTime; this covers them. Skips tables without the column.
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['users','addresses','orders','payments','coupons','shipments',
                           'agent_audit_log','outbox_events','payment_outbox_events']
  LOOP
    CONTINUE WHEN to_regclass(t) IS NULL OR NOT EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_schema = current_schema() AND table_name = t AND column_name = 'updated_at');
    EXECUTE format('DROP TRIGGER IF EXISTS set_updated_at ON %I', t);
    EXECUTE format('CREATE TRIGGER set_updated_at BEFORE UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION trg_set_updated_at()', t);
  END LOOP;
END $$;

-- ---------------------------------------------------------------------------
-- 3. Order status history
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS order_status_history (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id    uuid NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
  from_status varchar(20),
  to_status   varchar(20) NOT NULL,
  changed_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_order_status_history_order ON order_status_history (order_id, changed_at);

CREATE OR REPLACE FUNCTION trg_order_status_history() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    INSERT INTO order_status_history (order_id, from_status, to_status) VALUES (NEW.id, NULL, NEW.status);
  ELSIF NEW.status IS DISTINCT FROM OLD.status THEN
    INSERT INTO order_status_history (order_id, from_status, to_status) VALUES (NEW.id, OLD.status, NEW.status);
  END IF;
  RETURN NULL;
END $$;

DROP TRIGGER IF EXISTS order_status_history ON orders;
CREATE TRIGGER order_status_history AFTER INSERT OR UPDATE OF status ON orders
  FOR EACH ROW EXECUTE FUNCTION trg_order_status_history();

-- Orders that predate the trigger get one row for the status they are in now.
INSERT INTO order_status_history (order_id, from_status, to_status, changed_at)
SELECT o.id, NULL, o.status, o.created_at FROM orders o
WHERE NOT EXISTS (SELECT 1 FROM order_status_history h WHERE h.order_id = o.id);

-- ---------------------------------------------------------------------------
-- 4. A payment must match its order
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION trg_payment_matches_order() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE o record;
BEGIN
  SELECT amount, currency INTO o FROM orders WHERE id = NEW.order_id;
  IF FOUND AND (o.amount <> NEW.amount OR lower(o.currency) <> lower(NEW.currency)) THEN
    RAISE EXCEPTION 'payment % (% %) does not match order % (% %)',
      NEW.payment_id, NEW.amount, NEW.currency, NEW.order_id, o.amount, o.currency
      USING ERRCODE = 'check_violation';
  END IF;
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS payment_matches_order ON payments;
CREATE TRIGGER payment_matches_order BEFORE INSERT ON payments
  FOR EACH ROW EXECUTE FUNCTION trg_payment_matches_order();
