-- Relational integrity pass.
--
-- The live schema is a mix of the baseline (000001) and GORM AutoMigrate, so
-- every step is guarded and idempotent:
--   1. repair drift between baseline and the Go models
--   2. soft-delete-aware unique indexes
--   3. missing foreign keys   (NOT VALID, then VALIDATE; orphans only NOTICE)
--   4. CHECK constraints      (same NOT VALID / VALIDATE pattern)
--   5. coupon redemption record (coupon_usages)
--
-- Deliberately NOT done: notification_logs.user_id has no FK. It is an
-- append-only log written for any recipient, and an FK would make logging
-- fail (and the SQS message retry) whenever the user row is missing.
-- order_number and the idempotency_key columns stay plain unique (not
-- partial): they must stay unique even for soft-deleted rows.

CREATE OR REPLACE FUNCTION _col_exists(t text, c text) RETURNS boolean
LANGUAGE sql STABLE AS $$
  SELECT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = current_schema() AND table_name = t AND column_name = c)
$$;

-- ---------------------------------------------------------------------------
-- 1. Drift repair
-- ---------------------------------------------------------------------------

-- coupons: baseline used discount_type/discount_value and allowed NULLs, the Go
-- model + seed use type/value, deleted_at and NOT NULL expiry/limits.
ALTER TABLE coupons ADD COLUMN IF NOT EXISTS deleted_at timestamptz;

DO $$
BEGIN
  IF _col_exists('coupons', 'discount_type') THEN
    IF NOT _col_exists('coupons', 'type') THEN
      ALTER TABLE coupons RENAME COLUMN discount_type TO type;
      ALTER TABLE coupons RENAME COLUMN discount_value TO value;
    ELSE
      UPDATE coupons SET type = discount_type, value = discount_value WHERE type IS NULL;
      ALTER TABLE coupons DROP COLUMN discount_type, DROP COLUMN discount_value;
    END IF;
  END IF;
END $$;

UPDATE coupons SET type = 'flat' WHERE type = 'fixed'; -- 'fixed' is not a valid CouponType
UPDATE coupons SET min_order_value = 0 WHERE min_order_value IS NULL;
UPDATE coupons SET usage_limit = 0 WHERE usage_limit IS NULL; -- 0 = unlimited
UPDATE coupons SET expires_at = '9999-12-31 00:00:00+00' WHERE expires_at IS NULL;

ALTER TABLE coupons
  ALTER COLUMN type SET NOT NULL,
  ALTER COLUMN value TYPE numeric(12,2),
  ALTER COLUMN value SET NOT NULL,
  ALTER COLUMN min_order_value TYPE numeric(12,2),
  ALTER COLUMN min_order_value SET NOT NULL,
  ALTER COLUMN min_order_value SET DEFAULT 0,
  ALTER COLUMN usage_limit SET NOT NULL,
  ALTER COLUMN usage_limit SET DEFAULT 0,
  ALTER COLUMN expires_at SET NOT NULL;

-- orders: columns the Go model writes that the baseline never had; coupon_id
-- is the real link to coupons (coupon_code stays as a snapshot).
ALTER TABLE orders
  ADD COLUMN IF NOT EXISTS canceled_at timestamptz,
  ADD COLUMN IF NOT EXISTS completed_at timestamptz,
  ADD COLUMN IF NOT EXISTS coupon_id uuid;

CREATE INDEX IF NOT EXISTS idx_orders_coupon_id ON orders (coupon_id);

UPDATE orders o SET coupon_id = c.id
FROM coupons c
WHERE o.coupon_id IS NULL
  AND o.coupon_code IS NOT NULL AND o.coupon_code <> ''
  AND LOWER(c.code) = LOWER(o.coupon_code)
  AND c.deleted_at IS NULL;

-- shipments: legacy script had varchar order_id; baseline/seed use uuid.
DO $$
BEGIN
  IF (SELECT data_type FROM information_schema.columns
      WHERE table_schema = current_schema() AND table_name = 'shipments' AND column_name = 'order_id') <> 'uuid' THEN
    ALTER TABLE shipments ALTER COLUMN order_id TYPE uuid USING order_id::uuid;
  END IF;
  ALTER TABLE shipments ALTER COLUMN order_id SET NOT NULL;
EXCEPTION
  WHEN invalid_text_representation OR not_null_violation THEN
    RAISE NOTICE 'shipments.order_id not converted/NOT NULL: bad existing rows (%). Fix data and retry manually.', SQLERRM;
END $$;

-- notification_logs: Go model has bigint id + recipient/type/retry_count; the
-- baseline created a uuid id. Convert only when the uuid shape is present.
DO $$
BEGIN
  ALTER TABLE notification_logs
    ADD COLUMN IF NOT EXISTS recipient text,
    ADD COLUMN IF NOT EXISTS type text,
    ADD COLUMN IF NOT EXISTS retry_count integer NOT NULL DEFAULT 0;
  IF (SELECT data_type FROM information_schema.columns
      WHERE table_schema = current_schema() AND table_name = 'notification_logs' AND column_name = 'id') = 'uuid' THEN
    ALTER TABLE notification_logs ADD COLUMN id_new bigint GENERATED BY DEFAULT AS IDENTITY;
    ALTER TABLE notification_logs DROP COLUMN id;
    ALTER TABLE notification_logs RENAME COLUMN id_new TO id;
    ALTER TABLE notification_logs ADD PRIMARY KEY (id);
  END IF;
END $$;

-- ---------------------------------------------------------------------------
-- 2. Indexes
-- ---------------------------------------------------------------------------

-- Soft-deleted users/coupons must not block re-registration / re-creation.
-- GORM's `unique` tag makes constraints named uni_*; baseline made idx_*.
ALTER TABLE users DROP CONSTRAINT IF EXISTS uni_users_email;
ALTER TABLE users DROP CONSTRAINT IF EXISTS uni_users_phone_number;
DROP INDEX IF EXISTS idx_users_email;
DROP INDEX IF EXISTS idx_users_phone_number;
CREATE UNIQUE INDEX idx_users_email ON users (email) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX idx_users_phone_number ON users (phone_number) WHERE deleted_at IS NULL;

-- One case-insensitive unique index replaces the overlapping pair. Keeps the
-- name GORM's uniqueIndex tag expects so AutoMigrate does not recreate it.
DROP INDEX IF EXISTS idx_coupons_code;
DROP INDEX IF EXISTS idx_coupons_code_lower;
DROP INDEX IF EXISTS idx_coupons_active_expires; -- duplicate of idx_coupons_active
CREATE UNIQUE INDEX idx_coupons_code ON coupons (LOWER(code)) WHERE deleted_at IS NULL;

-- At most one succeeded payment per order (retries/failed attempts still allowed).
DO $$
BEGIN
  CREATE UNIQUE INDEX IF NOT EXISTS idx_payments_one_succeeded_per_order
    ON payments (order_id) WHERE status = 'succeeded' AND deleted_at IS NULL;
EXCEPTION WHEN unique_violation THEN
  RAISE NOTICE 'orders with >1 succeeded payment exist; idx_payments_one_succeeded_per_order not created. Investigate, then re-run.';
END $$;

-- ---------------------------------------------------------------------------
-- 3. Foreign keys
-- ---------------------------------------------------------------------------

-- Skips a column that already has any FK (GORM may have created users->addresses).
-- Orphans do not abort the migration: the FK is enforced for new writes and a
-- NOTICE says to clean up and run VALIDATE CONSTRAINT.
DO $$
DECLARE r record;
BEGIN
  FOR r IN SELECT * FROM (VALUES
    ('orders',          'orders_user_id_fkey',               'user_id',             'users',     'RESTRICT', ''),
    ('orders',          'orders_coupon_id_fkey',             'coupon_id',           'coupons',   'SET NULL', ''),
    ('payments',        'payments_order_id_fkey',            'order_id',            'orders',    'RESTRICT', ''),
    ('payments',        'payments_user_id_fkey',             'user_id',             'users',     'RESTRICT', ''),
    ('shipments',       'shipments_order_id_fkey',           'order_id',            'orders',    'RESTRICT', ''),
    ('users',           'users_billing_address_id_fkey',     'billing_address_id',  'addresses', 'SET NULL', 'DEFERRABLE INITIALLY DEFERRED'),
    ('users',           'users_shipping_address_id_fkey',    'shipping_address_id', 'addresses', 'SET NULL', 'DEFERRABLE INITIALLY DEFERRED'),
    ('agent_audit_log', 'agent_audit_log_user_id_fkey',      'user_id',             'users',     'SET NULL', ''),
    ('agent_audit_log', 'agent_audit_log_confirmed_by_fkey', 'confirmed_by',        'users',     'SET NULL', '')
  ) AS t(tbl, name, col, ref, on_del, extra)
  LOOP
    CONTINUE WHEN to_regclass(r.tbl) IS NULL OR NOT _col_exists(r.tbl, r.col);

    IF NOT EXISTS (
      SELECT 1 FROM pg_constraint c
      JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = ANY (c.conkey)
      WHERE c.contype = 'f' AND c.conrelid = to_regclass(r.tbl) AND a.attname = r.col
    ) THEN
      BEGIN
        EXECUTE format(
          'ALTER TABLE %I ADD CONSTRAINT %I FOREIGN KEY (%I) REFERENCES %I (id) ON DELETE %s %s NOT VALID',
          r.tbl, r.name, r.col, r.ref, r.on_del, r.extra);
      EXCEPTION WHEN datatype_mismatch THEN
        RAISE NOTICE 'skipped %: %.% type does not match %.id', r.name, r.tbl, r.col, r.ref;
        CONTINUE;
      END;
    END IF;

    BEGIN
      EXECUTE format('ALTER TABLE %I VALIDATE CONSTRAINT %I', r.tbl, r.name);
    EXCEPTION
      WHEN foreign_key_violation THEN
        RAISE NOTICE '% has orphan rows: enforced for new writes only. Clean up, then ALTER TABLE % VALIDATE CONSTRAINT %.', r.name, r.tbl, r.name;
      WHEN undefined_object THEN NULL; -- pre-existing FK has a different name
    END;
  END LOOP;
END $$;

-- ---------------------------------------------------------------------------
-- 4. CHECK constraints
-- ---------------------------------------------------------------------------

-- Money is integer minor units (cents) everywhere; coupons.value is a percent
-- (0-100) or flat minor units.
DO $$
DECLARE r record;
BEGIN
  FOR r IN SELECT * FROM (VALUES
    ('orders',      'chk_orders_status',
       $c$status IN ('pending_payment','paid','payment_failed','shipped','delivered','completed','cancelled','refunded')$c$),
    ('orders',      'chk_orders_amounts',      'amount >= 0 AND discount_amount >= 0'),
    ('order_items', 'chk_order_items_values',  'quantity > 0 AND price >= 0'),
    ('payments',    'chk_payments_status',
       $c$status IN ('pending','succeeded','failed','refunded','canceled')$c$),
    ('payments',    'chk_payments_amount',     'amount >= 0'),
    ('coupons',     'chk_coupons_type',
       $c$type IN ('percentage','flat','freeshipping')$c$),
    ('coupons',     'chk_coupons_values',
       'value >= 0 AND min_order_value >= 0 AND usage_limit >= 0 AND used_count >= 0'),
    ('coupons',     'chk_coupons_percentage',  $c$type <> 'percentage' OR value <= 100$c$),
    ('coupons',     'chk_coupons_usage',       'usage_limit = 0 OR used_count <= usage_limit')
  ) AS t(tbl, name, expr)
  LOOP
    CONTINUE WHEN to_regclass(r.tbl) IS NULL;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = r.name AND conrelid = to_regclass(r.tbl)) THEN
      BEGIN
        EXECUTE format('ALTER TABLE %I ADD CONSTRAINT %I CHECK (%s) NOT VALID', r.tbl, r.name, r.expr);
      EXCEPTION WHEN undefined_column THEN
        RAISE NOTICE 'skipped %: column missing on %', r.name, r.tbl;
        CONTINUE;
      END;
    END IF;

    BEGIN
      EXECUTE format('ALTER TABLE %I VALIDATE CONSTRAINT %I', r.tbl, r.name);
    EXCEPTION WHEN check_violation THEN
      RAISE NOTICE '% has violating rows: enforced for new writes only. Fix data, then ALTER TABLE % VALIDATE CONSTRAINT %.', r.name, r.tbl, r.name;
    END;
  END LOOP;
END $$;

-- ---------------------------------------------------------------------------
-- 5. Coupon redemption record
-- ---------------------------------------------------------------------------

-- UNIQUE(order_id): one redemption per order, so a redelivered order_created
-- event cannot increment coupons.used_count twice. (coupon_id, user_id) index
-- supports per-user limits.
CREATE TABLE IF NOT EXISTS coupon_usages (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  coupon_id  uuid NOT NULL REFERENCES coupons (id) ON DELETE RESTRICT,
  order_id   uuid NOT NULL UNIQUE REFERENCES orders (id) ON DELETE RESTRICT,
  user_id    uuid NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_coupon_usages_coupon_user ON coupon_usages (coupon_id, user_id);

DROP FUNCTION _col_exists(text, text);
